name: Build and Deploy to Local Minikube

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted   # Must be your local machine running Minikube

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure Docker to use Minikube
      run: |
        eval $(minikube -p minikube docker-env)
        docker info

    - name: Build Docker image
      run: |
        docker build -t wisecow:latest .
        docker tag wisecow:latest wisecow:${{ github.sha }}

    - name: Apply namespace
      run: kubectl apply -f k8s/namespace.yaml

    - name: Apply ConfigMap
      run: kubectl apply -f k8s/configmap.yaml

    - name: Deploy application
      run: kubectl apply -f k8s/deployment.yaml

    - name: Deploy service
      run: kubectl apply -f k8s/service.yaml

    - name: Deploy ingress
      run: |
        minikube addons enable ingress
        kubectl apply -f k8s/ingress.yaml

    - name: Verify deployment
      run: |
        kubectl get all -n wisecow-app
        kubectl get svc -n wisecow-app
        kubectl get ingress -n wisecow-app

    - name: Print Application URL
      run: |
        MINIKUBE_IP=$(minikube ip)
        echo "Your app is running at: http://$MINIKUBE_IP:30080"
